version: "3.9"

services:
  db-postgres:
    image: postgres:13
    container_name: pixasearch-postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "user"
      POSTGRES_DB: "pixasearch"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - java-pixasearch

networks:
  java-pixasearch:
    driver: bridge

